package com.api.banco.core.domain;

public enum CodigoDesconto {

    NAOTEMDESCONTO, VALORFIXODATAINFORMADA, PERCENTUALDATAINFORMADA, VALORANTECIPACAODIACORRIDO, VALORANTECIPACAODIAUTIL, PERCENTUALVALORNOMINALDIACORRIDO, PERCENTUALVALORNOMINALDIAUTIL
}
