package com.api.banco.dataprovider.repository.entity;

public enum CodigoDescontoEntity {

    NAOTEMDESCONTO, VALORFIXODATAINFORMADA, PERCENTUALDATAINFORMADA, VALORANTECIPACAODIACORRIDO, VALORANTECIPACAODIAUTIL, PERCENTUALVALORNOMINALDIACORRIDO, PERCENTUALVALORNOMINALDIAUTIL
}
